import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { Hero } from 'components/Hero';
import styles from 'styles/Home.module.css';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main className={styles.main}>
      <section className={styles.hero}>
        <div className={styles.fixed}>
          <Hero />
        </div>
        <div className={styles.heroWrap}>
          <button className={styles.scrollButton} type="button">
            List of Projects &darr;
          </button>
        </div>
      </section>

      <section className={styles.list}>
        <div className={styles.container}>
          <div className={styles.grid}>
            <div className={styles.listBlock}>
              <span className={styles.legend}>Basic shapes</span>
              <ol>
                <li>
                  <Link href="/basic-shapes/cube">Cube</Link>
                </li>
                <li>
                  <Link href="/basic-shapes/sphere">Sphere</Link>
                </li>
              </ol>
            </div>
            <div className={styles.listBlock}>
              <span className={styles.legend}>Models</span>
              <ol>
                <li>
                  <Link href="/models/candle">Candle</Link>
                </li>
                <li>
                  <Link href="/models/cola">Cola</Link>
                </li>
                <li>
                  <Link href="/models/martini">A glass of Martini</Link>
                </li>
              </ol>
            </div>
          </div>
        </div>
      </section>
    </main>
  </div>
);

export default Home;
